pipeline{


agent any
stages{
       stage('compile stage'){
        steps{
       withMaven(maven : 'maven-3.5.3'){
           sh 'mvn clean compile'
       }
       }
       }


       stage('build stage'){
               steps{
              withMaven(maven : 'Maven'){
                  sh 'mvn build'
              }
              }
              }

              stage('install stage'){
                             steps{
                            withMaven(maven : 'Maven'){
                                sh 'mvn install'
                            }
                            }
                            }
}


}
